/**
 * Finding a real photo for a dish and storing it on the dish (Dish.real_photo).
 */
import { db } from '../db/db'
import { save } from '../db/repo'
import { realPhotoFor } from '../db/photos'
import { fileToCompressedDataUrl } from '../engine/image'
import { findRealDishPhoto } from '../sync/ai'
import type { Dish, DishRealPhoto } from '../types'

/** Finds a photo (skipping pages in `exclude`) and compresses it like an uploaded one. */
export async function fetchRealPhoto(dish: Dish, exclude: string[] = []): Promise<DishRealPhoto | null> {
  const found = await findRealDishPhoto(dish.name, dish.ingredients.map((i) => i.name), exclude)
  if (!found) return null
  const { image_data_url, ...credit } = found
  let image_url = image_data_url
  try {
    image_url = await fileToCompressedDataUrl(await (await fetch(image_data_url)).blob())
  } catch {
    // Keep the original if the browser can't re-encode it — still a valid photo.
  }
  return { ...credit, image_url }
}

// One search at a time: a bulk add queues its dishes instead of firing a
// burst of requests at the free photo archives and Groq.
let queue: Promise<unknown> = Promise.resolve()

/**
 * Fire-and-forget, like autoGenerateDishImage: a new dish gets a real photo
 * in the background. Skipped for a starter-library dish, which already has a
 * hand-picked one. Re-reads the row before writing so edits made meanwhile
 * survive.
 */
export function autoFindRealPhoto(dish: Dish): void {
  if (dish.real_photo || realPhotoFor(dish.name)) return
  queue = queue.then(async () => {
    const photo = await fetchRealPhoto(dish)
    if (!photo) return
    const current = await db.dishes.get(dish.id)
    if (current && !current.deleted_at && !current.real_photo) await save('dishes', { ...current, real_photo: photo })
  })
}
